<?php

namespace Database\Seeders;

use App\Models\Membrecia;
use Faker\Factory;
use Illuminate\Database\Seeder;

class MiembrosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '1144133869', 'nombre' => 'ALVARO EDUARDO', 'apellido' => 'OCAMPO PAZ', 'fecha_nacimiento' => '1989-12-19', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '3207236182', 'email' => 'aeopaz@gmail.com', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CALLE 9A #45S-54 BONANZA JAMUNDÍ', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '40775438', 'nombre' => 'NUBIA', 'apellido' => 'SOTELO GALLEGO', 'fecha_nacimiento' => '1972-01-06', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '3177393612', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CALLE 76 No. 26 G5 -04 NARANJOS 1', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '1143990436', 'nombre' => 'MARIA ALEJANDRA', 'apellido' => 'PRADA SOTELO', 'fecha_nacimiento' => '1997-12-08', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '3046550872', 'email' => 'maprada97@outlook.com', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CRA.26 G9 No. 73-52', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '31293409', 'nombre' => 'NUBY', 'apellido' => 'MALDONADO DE PRADA', 'fecha_nacimiento' => '1947-05-10', 'sexo' => 'F', 'estado_civil' => 'V', 'celular' => '3166801241', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CALLE 76 No. 26 G5 - 04 NARANJOS 1', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '38962468', 'nombre' => 'ROSINDA', 'apellido' => 'MALDONADO HERNÁNDEZ', 'fecha_nacimiento' => '1943-12-30', 'sexo' => 'F', 'estado_civil' => 'V', 'celular' => '3053365788', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CALLE 54 No. 8-22, LA BASE', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '29831401', 'nombre' => 'NELLY', 'apellido' => 'PRADA MALDONADO', 'fecha_nacimiento' => '1979-04-28', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '3166802405', 'email' => 'yllen@hotmail.com', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CALLE 76 No. 26 G5-04 NARANJOS 1', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'YUDITH SAMIRA', 'apellido' => 'ANGULO GOMEZ', 'fecha_nacimiento' => '1978-10-01', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26H4#73B-66', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '94439233', 'nombre' => 'ANDRES MIGUEL', 'apellido' => 'CORTEZ ZAMBRANO', 'fecha_nacimiento' => '1977-05-23', 'sexo' => 'M', 'estado_civil' => 'S', 'celular' => '3147951178', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA  26 G9 No. 73B-52 MARROQUIN 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'ARCELIANO', 'apellido' => 'PAZ VALENCIA', 'fecha_nacimiento' => '1955-07-12', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26 G10 No. 80-04 PISO 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '31261923', 'nombre' => 'ADELIA', 'apellido' => 'DIAZ TORRES', 'fecha_nacimiento' => '1949-12-11', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '3166473250', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26S #75-73 PISO 1 ALFONSO BONILLA ARAGÓN', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'AMPARO', 'apellido' => 'LÓPEZ VELEZ', 'fecha_nacimiento' => '1969-09-02', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26 G9 #73-31 PISO 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '30039368', 'nombre' => 'BLASINA', 'apellido' => 'MORENO GOMEZ', 'fecha_nacimiento' => '1980-12-20', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '3158506730', 'email' => 'blasigomez@hotmail.com', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRRERA 49 #18-59 SAN JUDAS', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'CLAUDIA LIZETH', 'apellido' => 'ORDOÑEZ QUEVEDO', 'fecha_nacimiento' => '1978-04-27', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26 G10 No. 80-04 PISO 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'MARIA DOLLY', 'apellido' => 'LOPEZ MORENO', 'fecha_nacimiento' => '1944-12-27', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA. 26C #73-31', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'EDER', 'apellido' => 'QUESADA GONZALEZ', 'fecha_nacimiento' => '1983-03-25', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Carrera 26S #75-73 PISO 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'MARISOL', 'apellido' => 'VALENCIA PAZ', 'fecha_nacimiento' => '1979-12-20', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26G10 #73B-67 PISO 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'MARIA EUGENIA', 'apellido' => 'LABRADA VANEGAS', 'fecha_nacimiento' => '1967-01-22', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26G11#73B-04', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '76316197', 'nombre' => 'FERNEY', 'apellido' => 'SALAZAR LASSO', 'fecha_nacimiento' => '1972-12-25', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '3147703293', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CRA. 26 G5 No. 75a-29 NARANJOS 1', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '34597032', 'nombre' => 'MARIA DAMARIS', 'apellido' => 'PAZ VALENCIA', 'fecha_nacimiento' => '1965-08-04', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '3128965317', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26 G10 #80-76 PISO 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'MARIA ESTHER', 'apellido' => 'DE LA ENCARNACIÓN', 'fecha_nacimiento' => '1963-04-01', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CALLE 114 #26J-107', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '31481383', 'nombre' => 'LUZ ENELIA', 'apellido' => 'ORDOÑEZ C.', 'fecha_nacimiento' => '1966-10-13', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '3136193917', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CRA. 26 G10 No. 73-73, MARROQUIN 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'JOSE LUIS', 'apellido' => 'QUIÑONEZ MONTAÑO', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'M', 'estado_civil' => 'S', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CALLE 86# 7B-BIS25', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'MARIA NANCY', 'apellido' => 'QUIÑONEZ', 'fecha_nacimiento' => '1968-11-20', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CALLE 86 #7B-25', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'DEMBER STIVEN', 'apellido' => 'CASAS ANGULO', 'fecha_nacimiento' => '2007-05-25', 'sexo' => 'M', 'estado_civil' => 'S', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26H4#73B-66', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '34594862', 'nombre' => 'LIDA RUTH', 'apellido' => 'PAZ VALENCIA', 'fecha_nacimiento' => '1960-08-03', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Carrera 26 G9 No. 73-52, MARROQUIN 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '16688527', 'nombre' => 'FLAVIO GUILLERMO', 'apellido' => 'OCAMPO TENORIO', 'fecha_nacimiento' => '1961-10-19', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '3147234551', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CRA. 26 G9 No. 73-52 MARROQUIN 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '31939801', 'nombre' => 'LUZ MARINA', 'apellido' => 'ORTÍZ', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Pendiente', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '34508570', 'nombre' => 'MARTHA NELLY', 'apellido' => 'PAZ VALENCIA', 'fecha_nacimiento' => '1958-10-22', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '3233108276', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26G10 #73B-67 PISO 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '16744925', 'nombre' => 'WILMAR', 'apellido' => 'PRADA MALDONADO', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CALLE 76 No. 26 G5-04 NARANJOS 1', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '29688445', 'nombre' => 'FLOR', 'apellido' => 'MUÑOZ', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '3234774011', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Transversal 29 No. 4e-53', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '1062078767', 'nombre' => 'GLORIA MARIA', 'apellido' => 'PAJOY', 'fecha_nacimiento' => '1967-01-04', 'sexo' => 'F', 'estado_civil' => 'V', 'celular' => '3175225908', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CRA. 26G4 #76-76 NARANJOS 1', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '16240477', 'nombre' => 'MOISÉS', 'apellido' => 'OBANDO', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '3225414605', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CALLE 114#26J-107, MANUELA BELTRAN', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '31566196', 'nombre' => 'MILLERLANDY', 'apellido' => 'PRECIADO', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '3186679558', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26 G 1 No. 75-12, NARANJOS 1', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '1107059018', 'nombre' => 'HASSAN NASSAR', 'apellido' => 'FRANCO CHAVEZ', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Carrera 8a No. 13-81 Local 110', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'DANIEL', 'apellido' => 'LERMA ZEA', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CRA.26H3 #72W22', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'IRMA CLARA', 'apellido' => 'CAPOTE OROZCO', 'fecha_nacimiento' => '1961-02-06', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26H3 #72W-22', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '25410184', 'nombre' => 'LEONISA', 'apellido' => 'CAMILO', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'V', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Calle 114#26 J 107', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '1130675993', 'nombre' => 'LEIDY VIVIANA', 'apellido' => 'BERNAL DÍAZ', 'fecha_nacimiento' => '1988-04-17', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '3203707202', 'email' => 'jta.leidy@hotmail.com', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Carrera 26 s # 75-73', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '38556117', 'nombre' => 'NIRZAN MARIA', 'apellido' => 'ARBOLEDA CIFUENTES', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '3017865286', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA  26 G9 No. 73-32, MARROQUIN 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'JOSE ANIBAL', 'apellido' => 'VALENCIA SANTIESTEBAN', 'fecha_nacimiento' => '2020-07-26', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA .26 G9 No. 73-32', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'AIDA', 'apellido' => 'CARDENAS', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '3227185456', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Pendiente', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '66949896', 'nombre' => 'ANA EIVA', 'apellido' => 'OBANDO MOSQUERA', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '3146562792', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA  26M 112-30 MANUELA BELTRÁN', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'SEGUNDO GONZALO', 'apellido' => 'ROSERO', 'fecha_nacimiento' => '1953-08-29', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26G7#73-18', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '1130654300', 'nombre' => 'JOSE STIVEN', 'apellido' => 'CAMPAZ', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'M', 'estado_civil' => 'S', 'celular' => '3144587483', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26 I 2 #72W-130 PISO 2  LOS LAGOS', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '31837040', 'nombre' => 'HERMINIA', 'apellido' => 'ROBLES', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26G11 N°73-74', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'SANDRA LILIANA', 'apellido' => 'VALVERDE HENAO', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '3173940517', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'DIAGONAL 26G11 #T87-10, MARROQUIN 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'PAOLA ANDREA', 'apellido' => 'GONZALEZ CAPOTE', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26H3 #72W-22 PISO 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '66968321', 'nombre' => 'MONICA JHOANA', 'apellido' => 'LOZANO HERRERA', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '3183259753', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CALLE 80T #103-27, NARANJOS 1', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '1107041214', 'nombre' => 'ISA VALENTINA', 'apellido' => 'FRANCO', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '3128596591', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Pendiente', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '31832290', 'nombre' => 'ANA GRACIELA', 'apellido' => 'CHAVEZ', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'V', 'celular' => '3185409772', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26 G9# 73-31 MARROQUIN 2', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CE', 'numero_documento' => '12176305', 'nombre' => 'ALFREDO', 'apellido' => 'ARIAS', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '3122469498', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Pendiente', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'MARIA LUZ', 'apellido' => 'SANDOVAL', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Pendiente', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'VIVIANA', 'apellido' => 'CAPOTE', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Pendiente', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'HAYDEE', 'apellido' => 'SEGOVIA', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Pendiente', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'WILBER', 'apellido' => 'PEREA', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'M', 'estado_civil' => 'C', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Pendiente', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '38989237', 'nombre' => 'GUADALUPE', 'apellido' => 'TENORIO', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26 G12 # 80-25', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => 'Pendiente', 'nombre' => 'CLAUDIA', 'apellido' => 'LOAIZA', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '1111111111', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'Pendiente', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);
        Membrecia::create(['tipo_documento' => 'CC', 'numero_documento' => '38590263', 'nombre' => 'AMALIA', 'apellido' => 'SANCHEZ VIVERES', 'fecha_nacimiento' => '2022-12-13', 'sexo' => 'F', 'estado_civil' => 'S', 'celular' => '3176741682', 'email' => 'Pendiente', 'ciudad' => 'Cali', 'barrio' => 'Marroquin II', 'direccion' => 'CARRERA 26G10 #73-03', 'fecha_conversion' => '2001-10-21', 'estado' => 'A', 'id_usuario' => '1',]);


        // $faker = Factory::create('es_VE');
        // for ($i = 0; $i < 50; $i++) {
        //     $miembro = Membrecia::create();
        //     $miembro->tipo_documento = $faker->randomElement(['CC', 'CE', 'PS', 'TI']);
        //     $miembro->numero_documento = rand(111111, 9999999999);
        //     $miembro->nombre = $faker->firstNameFemale();
        //     $miembro->apellido = $faker->lastName;
        //     $miembro->fecha_nacimiento = $faker->date('Y-m-d');
        //     $miembro->fecha_conversion = $faker->date('Y-m-d');
        //     $miembro->sexo = $faker->randomElement(['F', 'M']);
        //     $miembro->estado_civil = $faker->randomElement(['S', 'C', 'D', 'U', 'V']);
        //     $miembro->celular = rand(1111111111, 9999999999);
        //     $miembro->email = $faker->email();
        //     $miembro->ciudad = $faker->randomElement(['Cali', 'Jamundi', 'Palmira', 'Candelaria', 'Bogota']);
        //     $miembro->barrio = $faker->randomElement(['Naranjos', 'Bonanza', 'Marroquin II', 'Alirio Mora', 'Decepaz']);
        //     $miembro->direccion = $faker->address();
        //     $miembro->id_usuario = 1;
        //     $miembro->save();
        // }
    }
}
